version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade --user awscli
      - npm install
      - chmod u+x ./build/read-env.sh && sh build/read-env.sh
      - npm run build
  build:
    commands:
      - export BasiqBlinkBucketName=`node build/readBuildConf.js`
      - aws s3 sync dist s3://$BasiqBlinkBucketName/v1 --acl public-read
